### ISSUE TITLE
[1.20.1-8.0.0] Server crash - SyncFishMessage uses client-only class net.minecraft.client.Minecraft

### ISSUE THREAD

**Issue by TigerWalts** [baguchan/EarthMobs#44]
Server is crashing on start up when the network SyncFishMessage class is registered.

- https://gist.github.com/TigerWalts/b7a156a8b1445e9e3fa6916ce05f6d32

```
	Caused by 1: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
		at baguchan.earthmobsmod.EarthMobsMod.setupMessages(EarthMobsMod.java:84) ~[EarthMobs-1.20.1-8.0.0.jar%23282!/:1.20.1-8.0.0] {re:classloading,pl:rei_plugin_compatibilities:B}
		at baguchan.earthmobsmod.EarthMobsMod.<init>(EarthMobsMod.java:57) ~[EarthMobs-1.20.1-8.0.0.jar%23282!/:1.20.1-8.0.0] {re:classloading,pl:rei_plugin_compatibilities:B}
```

It's using the `net.minecraft.client.Minecraft` class which is not available server side:

https://github.com/baguchan/EarthMobs/blob/02c922f2421316a2864514974992b9011efbde85/src/main/java/baguchan/earthmobsmod/message/SyncFishMessage.java#L39-L53

**Comment by baguchan** [comment]
sorry for forgot that. It will fix in next update!
